#!/bin/bash

echo "Enter a number:"
read number

if [ "$number" -gt 0 ]; then
    echo "The number is positive."
elif [ "$number" -eq 0 ]; then
    echo "The number is zero."
else
    echo "The number is negative."
fi
